### ISSUE TITLE
Non-existent versions of UUID reported

### ISSUE THREAD

**Issue by wrycu** [silentsignal/burp-uuid#2]
If a request contains a UUID-like string reporting a non-real UUID version (e.g. 10), the extension reports version 10.  It'd be nice if it instead reported a fake version, perhaps as a higher severity level since it isn't actually following the spec.

**Comment by dnet** [comment]
Sounds like a nice idea, I'll put it on my to-do list. Obviously, if someone submits a pull request with this in it, I'd merge that, so if you have the time and means to do it, it'd be welcome.

**Comment by wrycu** [comment]
I'll whip something up tomorrow.  It looks like you already have code in place checking for valid versions, so it'll just be modifying the issue report.

**Comment by dnet** [comment]
I agree, it's doable just by modifying the issue report.

**Comment by dnet** [comment]
Have you managed to implement something?

**Comment by dnet** [comment]
Thanks for your contribution!
